name: DeployTest

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-run:
    name: VerifyExecution
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar o compilador C++
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Compilar o programa
        run: g++ -o hello main.cpp

      - name: Verificar saída do programa
        run: |
          echo "Executing the binary..."
          timeout 20s ./hello || [[ $? -eq 124 ]]
        continue-on-error: false  #fail if error
